### ISSUE TITLE
Possible Array overflow?

### ISSUE THREAD

**Issue by Sythelux** [runevision/LayerProcGen#5]
While porting the Array2D to Godot I had an Array out of bounds exception on this line:

https://github.com/Sythelux/LayerProcGen/blob/128565dc81f2e4f14e8d70e784e54907c06eccec/Samples/LayerProcGen/0.1.0/TerrainSample/Scripts/Utilities/Array2D.cs#L32

which I fixed with a Modulo. What happens is, that the loop, which calls it at some points calls it with y=257 and x=1 Width is 257 so it ends up calculating 66050, which is indeed above the bounds (Width(257)*Height(257)=66049). I fixed it with Modulo so it is wrapping around, but I was wondering, what happens in your code:

https://github.com/runevision/LayerProcGen/blob/8289c603c17024907c6b8a37171977cf79807d5b/Samples~/TerrainSample/Scripts/Utilities/PointerArray.cs#L79

is the pointer just wrapping around from itself or is my access just completely wrong, maybe you have time to have a look in the debugger, what happens on the unity side. I just wanted to put it there so that I won't forget it.

**Comment by runevision** [comment]
When a 2D array is internally stored as a 1D array (which they all are in the end, one way or another), indexing the 1D array with "y * Width + x" is standard. This assumes we store one row at a time.

If we have Width = 257 and Height = 257 (which means x can be 0 to 256 and y can be 0 to 256) then:
Indexing (1, 0) = 0 * 257 + 1 = 1 which is row 0, column 1.
Indexing (0, 1) = 1 * 257 + 0 = 257 which is row 1, column 0.

The maximum index is (256, 256) = 256 * 257 + 256 = 66048 which is one smaller than the size 66049 and thus indeed the last possible index in the 1D array.

If Height is 257 and the array is indexed with y = 257, then that is not a valid index since the y index has to be in the range 0 to 256 (both inclusive).

About your code introducing a modulo "y * Width % Width + x" I can't make sense of it. "y * Width % Width" is always zero so this means the y input is entirely ignored.

Let me know if this helps / makes sense.

**Comment by Sythelux** [comment]
I understand that.

but this function:

 https://github.com/runevision/LayerProcGen/blob/16122e2042cabd912494fecd4e07f188ea0421f8/Samples/TerrainSample/Scripts/Generation/Layers/LandscapeLayer.cs#L418-L424

is getting called with x=1 and z=256 at some point, when it is generating splats, which leads to a call of height[z+1,x] -> heights[257,1]. 

so inside the array it is calling y=257, x=1:
 Indexing (257, 1) = 257 * 257 + 1 = 66050 which is out of bounds.

Again this could be, because I made a mistake porting the code, but the call stack (I attached the image below) is the same in your implementation with the same values as I hadn't changed that code except for using Godot Arrays.

![grafik](https://github.com/runevision/LayerProcGen/assets/601797/8254692a-ee7d-47f6-b0d4-9516f5bbcb14)

**Comment by runevision** [comment]
Indeed, you are correct. I've fixed it in revision b01bc52:
https://github.com/runevision/LayerProcGen/commit/b01bc52537d3ffc6d6c2245ec6e2863745d276b0
